version: '3.1'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data:/data/wallet
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teo123
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local